### ISSUE TITLE
Latest version (6.12.0) doesn't work

### ISSUE THREAD

**Issue by djonas3** [jiridudekusy/uucloud-cli#1]
When trying to use the latest version, any command will result in:

`SyntaxError: Invalid regular expression: /^ues:(?<ter_code>[\w\d\.\-]*?)?(\[(?<ter_oid>[\w\d]*?)?\])?:(?<art_code>[\w\d\.\-]*?)?(\[(?<art_oid>[\w\d]*?)?\])?(:(?<obj_code>[\w\d\.\-]*?)?(\[(?<obj_oid>[\w\d]*?)?\])?)?$/:
 Invalid group
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\uucloud-cli\src\misc\ues-uri.js:1:84)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\uucloud-cli\src\tasks\logs.js:8:16)
    at Module._compile (module.js:653:30)`

**Comment by jiridudekusy** [comment]
You have to use NodeJS version >= 10.
